version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 09106850351
      MYSQL_DATABASE: srhub
    ports:
      - 3306:3306

  app:
    build: 
      context: ./django
    ports:
      - 8000:8000
    volumes:
      - ./django/app:/app
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080